const emeraldDark = {
  primary: '#1eb854',
  'primary-focus': '#178c40',
  'primary-content': '#ffffff',
  secondary: '#1fd65f',
  'secondary-focus': '#18aa4b',
  'secondary-content': '#ffffff',
  accent: '#d99330',
  'accent-focus': '#b57721',
  'accent-content': '#ffffff',
  neutral: '#110e0e',
  'neutral-focus': '#060404',
  'neutral-content': '#ffffff',
  'base-100': '#1c1c1c',
  'base-200': '#262626',
  'base-300': '#1c1c1c',
  'base-content': '#ffffff',
  info: '#66c6ff',
  success: '#87d039',
  warning: '#e2d562',
  error: '#ff6f6f',
  '--border-color': 'var(--b3)',
  '--rounded-box': '1rem',
  '--rounded-btn': '0.5rem',
  '--rounded-badge': '1.9rem',
  '--animation-btn': '0',
  '--animation-input': '0',
  '--btn-text-case': 'uppercase',
  '--btn-focus-scale': '1',
  '--navbar-padding': '.5rem',
  '--border-btn': '1px',
  '--tab-border': '1px',
  '--tab-radius': '0.5rem',
}

module.exports = {
  styled: true,
  themes: [
    'emerald',
    {
      'emerald-dark': emeraldDark,
    },
  ],
  base: true,
  logs: true,
  rtl: false,
  utils: true,
}
