[build.environment]
  NODE_VERSION = "18"

[build]
  command = "pnpm run:build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"
