[build.environment]
  NODE_VERSION = "16"
  NPM_FLAGS = "--prefix=/dev/null"

[build]
  publish = "dist"
  command = "npx pnpm i -r --store=node_modules/.pnpm-store && npx pnpm run:build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"
