name: Test

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [16.15.1]
        os: [ubuntu-latest]
      fail-fast: false

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3.0.3
        with:
          path: |
            ~/.cache
          key: cypress-cache-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}
      - uses: pnpm/action-setup@v2.2.1
        with:
          version: latest
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Static Analysis
        run: pnpm lint

      - name: Build SPA Distribution
        run: pnpm build:prod:spa

      - name: Build SSG Distribution
        run: pnpm build:prod:ssg

      - name: Vitest Unit and Integration Test Runner
        run: pnpm test:vitest:ci

      - name: Cypress PNPM Patch
        run: cp pnpm-lock.yaml package-lock.json

      # Disabled until Cypress CT tests are added
      # - name: Cypress Component Test Runner
      #   uses: cypress-io/github-action@v4
      #   with:
      #     component: true
      #     install: false

      - name: Cypress End-to-End Test Runner
        uses: cypress-io/github-action@v4
        with:
          browser: chrome
          install-command: echo
          build: pnpm run:build
          component: false
          start: pnpm preview
